export const texts = {
  es: {
    seo: {
      title: 'Liwaisi Tech | Tecnología Práctica para el Comercio Rural · Soki AI',
      keywords: 'Liwaisi Tech, Soki AI, tecnologia, asistente comercial WhatsApp, registro de ventas, control de caja, Casanare, Aguazul, Mani',
      ogTitle: 'Liwaisi Tech | Empodera tu Negocio Rural con Tecnología Práctica',
      ogDescription: 'Conoce Soki by Liwaisi: asistente comercial automático en WhatsApp. Piloto cerrado para comerciantes rurales.',
    },
    a11y: {
      brandLinkAria: 'Ir al inicio de Liwaisi Tech',
      brandLogoAlt: 'Logo oficial de Liwaisi Tech',
      navDesktopAria: 'Navegación principal',
      navMobileAria: 'Menú móvil',
      menuToggleOpenAria: 'Abrir menú de navegación',
      modalCloseAria: 'Cerrar ventana emergente',
      socialFacebookAria: 'Seguir a Liwaisi en Facebook',
      socialGithubAria: 'Ver repositorios de Liwaisi en GitHub',
      socialInstagramAria: 'Seguir a Liwaisi en Instagram',
      socialLinkedinAria: 'Conectar con Liwaisi en LinkedIn',
      heroImageAlt: 'Soki by Liwaisi - Asistente comercial con inteligencia artificial en WhatsApp',
    },
    navbar: {
      brand: 'LIWAISI TECH',
      home: 'Inicio',
      product: 'Producto (Soki)',
      impact: 'Impacto',
      pilot: 'Únete al Piloto',
      themeLight: 'Modo Claro',
      themeDark: 'Modo Oscuro',
    },
    hero: {
      title: 'Empodera tu Negocio con Tecnología Práctica.',
      subtitle: 'Conoce "Soki AI by Liwaisi", tu asistente comercial automático en WhatsApp. (Actualmente en fase de piloto cerrado para comerciantes de Casanare).',
      cta: 'POSTULA TU NEGOCIO AL PILOTO.',
      imageDesktop: '/assets/images/hero-desktop.webp',
      imageMobile: '/assets/images/hero-mobile.webp',
    },
    features: {
      title: 'Tecnología que Impulsa tu Comercio.',
      card1: 'Registro de Ventas y Fiados.',
      card2: 'Control de Caja Diario.',
      card3: 'Análisis de Rentabilidad.',
      card4: 'Interacción nativa en WhatsApp.',
    },
    impact: {
      title: 'Impacto en el Territorio',
      btnCaseStudy: 'Ver Caso de Éxito',
      cases: {
        case1: {
          title: 'Cafetería La Casaba (Casanare)',
          image: '/assets/images/cafeteria-la-casaba-desktop.webp',
          alt: 'Cafetería La Casaba en Casanare utilizando Soki AI',
          description: 'Negocio de café y alimentos en Casanare que implementó Soki AI para optimizar su administración diaria sin cuadernos ni pérdidas de información.',
          points: [
            'Registro ágil de ventas diarias y control de cuentas fiadas en tiempo real.',
            'Cierre de caja diario automático con balance claro de entradas y salidas.',
            'Gestión 100% asistida a través de WhatsApp sin instalar programas complejos.',
          ],
        },
        case2: {
          title: 'Bootcamp Huertics',
          image: '/assets/images/cafe-aguazul.webp',
          alt: 'Bootcamp Huertics Cali Colombia',
          description: 'Bootcamp ejecutado en la institucion Nuevo Latir en Disrito de Aguablanca Cali Colombia.',
          points: [
            'Bootcamp ejecutado en asociacion con empresa Rincon Verde, OMLATAM y LIWAISI.',
            'Este Programa se ejecuto durante 1 semana entregando conocimiento en tecnología, habilidades de liderazgo e innovación aplicable y resiliente',
            'Ademas de la instalación de uns sistema de monitoreo automatizado de riego para la huerta del colegio bajo el cuidado de los estudiantes del programa LectuHuerta.',
          ],
        },
        case3: {
          title: 'Talleres y charlas en colegios de Maní (Casanare)',
          image: '/assets/images/bootcamp-huertics.webp',
          alt: 'Sesión de formación técnica y Bootcamp Huertics en Maní',
          description: 'Llevamos 2 años con nuestros talleres y mentorías brindando apoyo y/o co-creando con jóvenes y comunidades.',
          points: [
            'Hemos llegado a 3 instituciones educativas rurales con charlas y talleres sobre uso de la IA.',
            'Impactamos a más de 300 estudiantes con talleres y bootcamp en el uso tecnologías, habilidades de liderazgo e innovación aplicable y resilientes en zonas rurales de Mani Casanare.',
            'Brindamos apoyo constante a 3 emprendimientos, a través de más de 100 horas de mentorías personalizadas para que adapten y usen herramientas tecnológicas que potencian sus modelos de negocio.',
          ],
        },
      },
    },
    capture: {
      title: 'Postula tu negocio al Piloto de Soki.',
      description: 'Los cupos son limitados. Déjanos tus datos y evaluaremos si tu negocio cumple con los requisitos técnicos para esta fase.',
      nameLabel: 'Nombre Completo *',
      namePlaceholder: 'Ej. Carlos Mendoza',
      emailLabel: 'Correo Electrónico *',
      emailPlaceholder: 'Ej. carlos.mendoza@gmail.com',
      businessTypeLabel: 'Tipo de Negocio *',
      businessTypePlaceholder: 'Ej. Tienda de Abarrotes, Ferretería, Cafetería',
      municipalityLabel: 'Municipio *',
      municipalityPlaceholder: 'Ej. Maní, Aguazul, Yopal',
      whatsappLabel: 'Número de WhatsApp *',
      whatsappPlaceholder: 'Ej. 314 227 3180',
      submitButton: 'SOLICITAR ACCESO ANTICIPADO',
      submittingButton: 'ENVIANDO SOLICITUD...',
      requiredValidation: 'Por favor completa todos los campos requeridos.',
      feedbackSuccessTitle: '¡Postulación enviada con éxito!',
      feedbackSuccessDesc: 'Hemos recibido los datos de tu negocio. Evaluaremos los requisitos técnicos y te contactaremos a tu correo electrónico.',
      feedbackErrorTitle: 'No se pudo enviar la postulación',
      feedbackErrorDesc: 'Ocurrió un error al procesar el envío. Por favor escríbenos directamente a liwaisitech@gmail.com',
    },
    footer: {
      companyName: 'LIWAISI TECNOLOGIA RURAL SOSTENIBLE S.A.S.',
      nit: 'NIT: 902076671',
      address: 'Dirección: Vereda el Guineo, Finca Los Guarataros. Aguazul Casanare',
      privacyLink: 'Política de Privacidad Soki AI',
      termsLink: 'Términos de Servicio Soki AI',
      follow: 'Sigue a Liwaisi',
      contact: 'Contacto',
      email: 'liwaisitech@gmail.com',
      legal: '© 2026 Todos los derechos reservados | Políticas de Privacidad.',
      claim: 'Liwaisi Innova, Conecta y Transforma.',
      copyright: '© 2026 Liwaisi Tecnología Rural Sostenible S.A.S. Todos los derechos reservados.',
    },
  },
  en: {
    seo: {
      title: 'Liwaisi Tech | Practical Technology for Rural Commerce · Soki AI',
      description: 'Empower your rural business with Soki by Liwaisi, the automatic commercial assistant on WhatsApp for cash control, sales tracking, and customer credit in Casanare.',
      keywords: 'Liwaisi Tech, Soki AI, rural technology, WhatsApp commercial assistant, sales tracking, cash control, Casanare, Aguazul, Mani',
      ogTitle: 'Liwaisi Tech | Empower your Rural Business with Practical Technology',
      ogDescription: 'Meet Soki by Liwaisi: automated commercial assistant on WhatsApp. Closed pilot for rural merchants.',
    },
    a11y: {
      brandLinkAria: 'Go to Liwaisi Tech home',
      brandLogoAlt: 'Official Liwaisi Tech logo',
      navDesktopAria: 'Main navigation',
      navMobileAria: 'Mobile navigation menu',
      menuToggleOpenAria: 'Open navigation menu',
      modalCloseAria: 'Close modal dialog',
      socialFacebookAria: 'Follow Liwaisi on Facebook',
      socialGithubAria: 'View Liwaisi repositories on GitHub',
      socialInstagramAria: 'Follow Liwaisi on Instagram',
      socialLinkedinAria: 'Connect with Liwaisi on LinkedIn',
      heroImageAlt: 'Soki by Liwaisi - AI Commercial Assistant on WhatsApp',
    },
    navbar: {
      brand: 'LIWAISI TECH',
      home: 'Home',
      product: 'Product (Soki)',
      impact: 'Impact',
      pilot: 'Join Pilot',
      themeLight: 'Light Mode',
      themeDark: 'Dark Mode',
    },
    hero: {
      title: 'Empower your Rural Business with Practical Technology.',
      subtitle: 'Meet "Soki by Liwaisi", your automated commercial assistant on WhatsApp. (Currently in closed pilot for merchants in Casanare).',
      cta: 'APPLY YOUR BUSINESS TO THE PILOT.',
      imageDesktop: '/assets/images/hero-desktop.webp',
      imageMobile: '/assets/images/hero-mobile.webp',
    },
    features: {
      title: 'Technology that Powers your Business.',
      card1: 'Sales and Credit Tracking.',
      card2: 'Daily Cash Control.',
      card3: 'Profitability Analysis.',
      card4: 'Native WhatsApp Interaction.',
    },
    impact: {
      title: 'Impact in the Territory',
      btnCaseStudy: 'View Case Study',
      cases: {
        case1: {
          title: 'La Casaba Coffee Shop (Casanare)',
          image: '/assets/images/cafeteria-la-casaba-desktop.webp',
          alt: 'La Casaba Coffee Shop in Casanare using Soki AI',
          description: 'Coffee and food business in Casanare that implemented Soki AI to optimize daily management without paper notebooks or lost records.',
          points: [
            'Fast logging of daily sales and real-time customer credit tracking.',
            'Automatic daily cash close with a clear balance of income and expenses.',
            '100% assisted management via WhatsApp without complex software.',
          ],
        },
        case2: {
          title: 'Coffee Shop in Aguazul',
          image: '/assets/images/cafe-aguazul.webp',
          alt: 'Local coffee shop in Aguazul Casanare',
          description: 'Local business in Aguazul that eliminated cash discrepancies and improved tracking of best-selling products.',
          points: [
            'Automatic categorization of income and inventory purchases.',
            'Clear profit margin visibility delivered right in the chat.',
            'Simple and accessible commercial operations for the entire team.',
          ],
        },
        case3: {
          title: 'Workshop Bootcamp in Maní (Casanare)',
          image: '/assets/images/bootcamp-huertics.webp',
          alt: 'Technical training session and Huertics Bootcamp in Maní',
          description: 'We have been providing support and/or co-creating with young people and communities for 1 year through workshops, mentoring, and bootcamps.',
          points: [
            'We have reached 2 rural educational institutions with talks and workshops on the use of AI.',
            'We impacted more than 200 students with workshops and bootcamps on the use of technologies, leadership skills, and applicable, resilient innovation. Both in urban and rural areas.',
            'We provide constant support to 3 ventures and 5 entrepreneurs through more than 100 hours of personalized mentoring to adapt and use tech tools that empower their business ideas.',
          ],
        },
      },
    },
    capture: {
      title: 'Apply your business to the Soki Pilot.',
      description: 'Slots are limited. Leave your details and we will evaluate if your business meets the technical requirements.',
      nameLabel: 'Full Name *',
      namePlaceholder: 'E.g. Carlos Mendoza',
      emailLabel: 'Email Address *',
      emailPlaceholder: 'E.g. carlos.mendoza@gmail.com',
      businessTypeLabel: 'Business Type *',
      businessTypePlaceholder: 'E.g. Grocery Store, Hardware, Coffee Shop',
      municipalityLabel: 'Municipality *',
      municipalityPlaceholder: 'E.g. Maní, Aguazul, Yopal',
      whatsappLabel: 'WhatsApp Number *',
      whatsappPlaceholder: 'E.g. +57 314 227 3180',
      submitButton: 'REQUEST EARLY ACCESS',
      submittingButton: 'SUBMITTING APPLICATION...',
      requiredValidation: 'Please complete all required fields.',
      feedbackSuccessTitle: 'Application submitted successfully!',
      feedbackSuccessDesc: 'We received your business information. We will evaluate technical requirements and contact you via email.',
      feedbackErrorTitle: 'Could not submit application',
      feedbackErrorDesc: 'An error occurred during submission. Please contact us directly at liwaisitech@gmail.com',
    },
    footer: {
      companyName: 'LIWAISI TECNOLOGIA RURAL SOSTENIBLE S.A.S.',
      nit: 'NIT: 902076671',
      address: 'Address: Vereda el Guineo, Finca Los Guarataros. Aguazul Casanare',
      privacyLink: 'Soki AI Privacy Policy',
      termsLink: 'Soki AI Terms of Service',
      follow: 'Follow Liwaisi',
      contact: 'Contact',
      email: 'liwaisitech@gmail.com',
      legal: '© 2026 All rights reserved | Privacy Policy.',
      claim: 'Liwaisi Innovates, Connects and Transforms.',
      copyright: '© 2026 Liwaisi Tecnología Rural Sostenible S.A.S. All rights reserved.',
    },
  },
} as const;